# -*- coding: utf-8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *


metadata = MetaData()


agtAgentTypes =  Table('agtAgentTypes', metadata,
    Column('agentTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('agentType', VARCHAR(length=50), primary_key=False)
    )


agtAgents =  Table('agtAgents', metadata,
    Column('agentID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('divisionID', INTEGER(), primary_key=False),
            Column('corporationID', INTEGER(), primary_key=False),
            Column('locationID', INTEGER(), primary_key=False),
            Column('level', INTEGER(), primary_key=False),
            Column('quality', INTEGER(), primary_key=False),
            Column('agentTypeID', INTEGER(), primary_key=False),
            Column('isLocator', INTEGER(), primary_key=False),


    )


agtResearchAgents =  Table('agtResearchAgents', metadata,
    Column('agentID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


certCerts =  Table('certCerts', metadata,
    Column('certID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('description', TEXT(), primary_key=False),
            Column('groupID', INTEGER(), primary_key=False),
            Column('name', VARCHAR(length=255), primary_key=False),


    )


certMasteries =  Table('certMasteries', metadata,
    Column('typeID', INTEGER(), primary_key=False),
            Column('masteryLevel', INTEGER(), primary_key=False),
            Column('certID', INTEGER(), primary_key=False),


    )


certSkills =  Table('certSkills', metadata,
    Column('certID', INTEGER(), primary_key=False),
            Column('skillID', INTEGER(), primary_key=False),
            Column('certLevelInt', INTEGER(), primary_key=False),
            Column('skillLevel', INTEGER(), primary_key=False),
            Column('certLevelText', VARCHAR(length=8), primary_key=False),


    )


chrAncestries =  Table('chrAncestries', metadata,
    Column('ancestryID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('ancestryName', VARCHAR(length=100), primary_key=False),
            Column('bloodlineID', INTEGER(), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('perception', INTEGER(), primary_key=False),
            Column('willpower', INTEGER(), primary_key=False),
            Column('charisma', INTEGER(), primary_key=False),
            Column('memory', INTEGER(), primary_key=False),
            Column('intelligence', INTEGER(), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('shortDescription', VARCHAR(length=500), primary_key=False),


    )


chrAttributes =  Table('chrAttributes', metadata,
    Column('attributeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('attributeName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('shortDescription', VARCHAR(length=500), primary_key=False),
            Column('notes', VARCHAR(length=500), primary_key=False),


    )


chrBloodlines =  Table('chrBloodlines', metadata,
    Column('bloodlineID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('bloodlineName', VARCHAR(length=100), primary_key=False),
            Column('raceID', INTEGER(), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('maleDescription', VARCHAR(length=1000), primary_key=False),
            Column('femaleDescription', VARCHAR(length=1000), primary_key=False),
            Column('shipTypeID', INTEGER(), primary_key=False),
            Column('corporationID', INTEGER(), primary_key=False),
            Column('perception', INTEGER(), primary_key=False),
            Column('willpower', INTEGER(), primary_key=False),
            Column('charisma', INTEGER(), primary_key=False),
            Column('memory', INTEGER(), primary_key=False),
            Column('intelligence', INTEGER(), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('shortDescription', VARCHAR(length=500), primary_key=False),
            Column('shortMaleDescription', VARCHAR(length=500), primary_key=False),
            Column('shortFemaleDescription', VARCHAR(length=500), primary_key=False),


    )


chrFactions =  Table('chrFactions', metadata,
    Column('factionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('factionName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('raceIDs', INTEGER(), primary_key=False),
            Column('solarSystemID', INTEGER(), primary_key=False),
            Column('corporationID', INTEGER(), primary_key=False),
            Column('sizeFactor', FLOAT(), primary_key=False),
            Column('stationCount', INTEGER(), primary_key=False),
            Column('stationSystemCount', INTEGER(), primary_key=False),
            Column('militiaCorporationID', INTEGER(), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),


    )


chrRaces =  Table('chrRaces', metadata,
    Column('raceID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('raceName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('shortDescription', VARCHAR(length=500), primary_key=False),


    )


crpActivities =  Table('crpActivities', metadata,
    Column('activityID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('activityName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),


    )


crpNPCCorporationDivisions =  Table('crpNPCCorporationDivisions', metadata,
    Column('corporationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('divisionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('size', INTEGER(), primary_key=False),


    )


crpNPCCorporationResearchFields =  Table('crpNPCCorporationResearchFields', metadata,
    Column('skillID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('corporationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


crpNPCCorporationTrades =  Table('crpNPCCorporationTrades', metadata,
    Column('corporationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


crpNPCCorporations =  Table('crpNPCCorporations', metadata,
    Column('corporationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('size', CHAR(length=1), primary_key=False),
            Column('extent', CHAR(length=1), primary_key=False),
            Column('solarSystemID', INTEGER(), primary_key=False),
            Column('investorID1', INTEGER(), primary_key=False),
            Column('investorShares1', INTEGER(), primary_key=False),
            Column('investorID2', INTEGER(), primary_key=False),
            Column('investorShares2', INTEGER(), primary_key=False),
            Column('investorID3', INTEGER(), primary_key=False),
            Column('investorShares3', INTEGER(), primary_key=False),
            Column('investorID4', INTEGER(), primary_key=False),
            Column('investorShares4', INTEGER(), primary_key=False),
            Column('friendID', INTEGER(), primary_key=False),
            Column('enemyID', INTEGER(), primary_key=False),
            Column('publicShares', INTEGER(), primary_key=False),
            Column('initialPrice', INTEGER(), primary_key=False),
            Column('minSecurity', FLOAT(), primary_key=False),
            Column('scattered', INTEGER(), primary_key=False),
            Column('fringe', INTEGER(), primary_key=False),
            Column('corridor', INTEGER(), primary_key=False),
            Column('hub', INTEGER(), primary_key=False),
            Column('border', INTEGER(), primary_key=False),
            Column('factionID', INTEGER(), primary_key=False),
            Column('sizeFactor', FLOAT(), primary_key=False),
            Column('stationCount', INTEGER(), primary_key=False),
            Column('stationSystemCount', INTEGER(), primary_key=False),
            Column('description', VARCHAR(length=4000), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),


    )


crpNPCDivisions =  Table('crpNPCDivisions', metadata,
    Column('divisionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('divisionName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('leaderType', VARCHAR(length=100), primary_key=False),


    )


dgmAttributeCategories =  Table('dgmAttributeCategories', metadata,
    Column('categoryID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('categoryName', VARCHAR(length=50), primary_key=False),
            Column('categoryDescription', VARCHAR(length=200), primary_key=False),


    )


dgmAttributeTypes =  Table('dgmAttributeTypes', metadata,
    Column('attributeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('attributeName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('defaultValue', FLOAT(), primary_key=False),
            Column('published', INTEGER(), primary_key=False),
            Column('displayName', VARCHAR(length=100), primary_key=False),
            Column('unitID', INTEGER(), primary_key=False),
            Column('stackable', INTEGER(), primary_key=False),
            Column('highIsGood', INTEGER(), primary_key=False),
            Column('categoryID', INTEGER(), primary_key=False),


    )


dgmEffects =  Table('dgmEffects', metadata,
    Column('effectID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('effectName', VARCHAR(length=400), primary_key=False),
            Column('effectCategory', INTEGER(), primary_key=False),
            Column('preExpression', INTEGER(), primary_key=False),
            Column('postExpression', INTEGER(), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('guid', VARCHAR(length=60), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('isOffensive', INTEGER(), primary_key=False),
            Column('isAssistance', INTEGER(), primary_key=False),
            Column('durationAttributeID', INTEGER(), primary_key=False),
            Column('trackingSpeedAttributeID', INTEGER(), primary_key=False),
            Column('dischargeAttributeID', INTEGER(), primary_key=False),
            Column('rangeAttributeID', INTEGER(), primary_key=False),
            Column('falloffAttributeID', INTEGER(), primary_key=False),
            Column('disallowAutoRepeat', INTEGER(), primary_key=False),
            Column('published', INTEGER(), primary_key=False),
            Column('displayName', VARCHAR(length=100), primary_key=False),
            Column('isWarpSafe', INTEGER(), primary_key=False),
            Column('rangeChance', INTEGER(), primary_key=False),
            Column('electronicChance', INTEGER(), primary_key=False),
            Column('propulsionChance', INTEGER(), primary_key=False),
            Column('distribution', INTEGER(), primary_key=False),
            Column('sfxName', VARCHAR(length=20), primary_key=False),
            Column('npcUsageChanceAttributeID', INTEGER(), primary_key=False),
            Column('npcActivationChanceAttributeID', INTEGER(), primary_key=False),
            Column('fittingUsageChanceAttributeID', INTEGER(), primary_key=False),
            Column('modifierInfo', TEXT(), primary_key=False),


    )


dgmExpressions =  Table('dgmExpressions', metadata,
    Column('expressionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('operandID', INTEGER(), primary_key=False),
            Column('arg1', INTEGER(), primary_key=False),
            Column('arg2', INTEGER(), primary_key=False),
            Column('expressionValue', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('expressionName', VARCHAR(length=500), primary_key=False),
            Column('expressionTypeID', INTEGER(), primary_key=False),
            Column('expressionGroupID', INTEGER(), primary_key=False),
            Column('expressionAttributeID', INTEGER(), primary_key=False),


    )


dgmTypeAttributes =  Table('dgmTypeAttributes', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('attributeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('valueInt', INTEGER(), primary_key=False),
            Column('valueFloat', FLOAT(), primary_key=False),


    )


dgmTypeEffects =  Table('dgmTypeEffects', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('effectID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('isDefault', INTEGER(), primary_key=False),


    )


eveGraphics =  Table('eveGraphics', metadata,
    Column('graphicID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('sofFactionName', VARCHAR(length=100), primary_key=False),
            Column('graphicFile', VARCHAR(length=100), primary_key=False),
            Column('sofHullName', VARCHAR(length=100), primary_key=False),
            Column('sofRaceName', VARCHAR(length=100), primary_key=False),
            Column('description', TEXT(), primary_key=False),


    )


eveIcons =  Table('eveIcons', metadata,
    Column('iconID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('iconFile', VARCHAR(length=500), primary_key=False),
            Column('description', TEXT(), primary_key=False),


    )


eveUnits =  Table('eveUnits', metadata,
    Column('unitID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('unitName', VARCHAR(length=100), primary_key=False),
            Column('displayName', VARCHAR(length=50), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),


    )


industryActivity =  Table('industryActivity', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('activityID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('time', INTEGER(), primary_key=False),


    )


industryActivityMaterials =  Table('industryActivityMaterials', metadata,
    Column('typeID', INTEGER(), primary_key=False),
            Column('activityID', INTEGER(), primary_key=False),
            Column('materialTypeID', INTEGER(), primary_key=False),
            Column('quantity', INTEGER(), primary_key=False),


    )


industryActivityProbabilities =  Table('industryActivityProbabilities', metadata,
    Column('typeID', INTEGER(), primary_key=False),
            Column('activityID', INTEGER(), primary_key=False),
            Column('productTypeID', INTEGER(), primary_key=False),
            Column('probability', DECIMAL(precision=3, scale=2), primary_key=False),


    )


industryActivityProducts =  Table('industryActivityProducts', metadata,
    Column('typeID', INTEGER(), primary_key=False),
            Column('activityID', INTEGER(), primary_key=False),
            Column('productTypeID', INTEGER(), primary_key=False),
            Column('quantity', INTEGER(), primary_key=False),


    )


industryActivityRaces =  Table('industryActivityRaces', metadata,
    Column('typeID', INTEGER(), primary_key=False),
            Column('activityID', INTEGER(), primary_key=False),
            Column('productTypeID', INTEGER(), primary_key=False),
            Column('raceID', INTEGER(), primary_key=False),


    )


industryActivitySkills =  Table('industryActivitySkills', metadata,
    Column('typeID', INTEGER(), primary_key=False),
            Column('activityID', INTEGER(), primary_key=False),
            Column('skillID', INTEGER(), primary_key=False),
            Column('level', INTEGER(), primary_key=False),


    )


industryBlueprints =  Table('industryBlueprints', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('maxProductionLimit', INTEGER(), primary_key=False),


    )


invCategories =  Table('invCategories', metadata,
    Column('categoryID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('categoryName', VARCHAR(length=100), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('published', INTEGER(), primary_key=False),


    )


invContrabandTypes =  Table('invContrabandTypes', metadata,
    Column('factionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('standingLoss', FLOAT(), primary_key=False),
            Column('confiscateMinSec', FLOAT(), primary_key=False),
            Column('fineByValue', FLOAT(), primary_key=False),
            Column('attackMinSec', FLOAT(), primary_key=False),


    )


invControlTowerResourcePurposes =  Table('invControlTowerResourcePurposes', metadata,
    Column('purpose', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('purposeText', VARCHAR(length=100), primary_key=False),


    )


invControlTowerResources =  Table('invControlTowerResources', metadata,
    Column('controlTowerTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('resourceTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('purpose', INTEGER(), primary_key=False),
            Column('quantity', INTEGER(), primary_key=False),
            Column('minSecurityLevel', FLOAT(), primary_key=False),
            Column('factionID', INTEGER(), primary_key=False),


    )


invFlags =  Table('invFlags', metadata,
    Column('flagID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('flagName', VARCHAR(length=200), primary_key=False),
            Column('flagText', VARCHAR(length=100), primary_key=False),
            Column('orderID', INTEGER(), primary_key=False),


    )


invGroups =  Table('invGroups', metadata,
    Column('groupID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('categoryID', INTEGER(), primary_key=False),
            Column('groupName', VARCHAR(length=100), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('useBasePrice', INTEGER(), primary_key=False),
            Column('anchored', INTEGER(), primary_key=False),
            Column('anchorable', INTEGER(), primary_key=False),
            Column('fittableNonSingleton', INTEGER(), primary_key=False),
            Column('published', INTEGER(), primary_key=False),


    )


invItems =  Table('invItems', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=False, nullable=False),
            Column('ownerID', INTEGER(), primary_key=False, nullable=False),
            Column('locationID', INTEGER(), primary_key=False, nullable=False),
            Column('flagID', INTEGER(), primary_key=False, nullable=False),
            Column('quantity', INTEGER(), primary_key=False, nullable=False),


    )


invMarketGroups =  Table('invMarketGroups', metadata,
    Column('marketGroupID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('parentGroupID', INTEGER(), primary_key=False),
            Column('marketGroupName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=3000), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('hasTypes', INTEGER(), primary_key=False),


    )


invMetaGroups =  Table('invMetaGroups', metadata,
    Column('metaGroupID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('metaGroupName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),


    )


invMetaTypes =  Table('invMetaTypes', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('parentTypeID', INTEGER(), primary_key=False),
            Column('metaGroupID', INTEGER(), primary_key=False),


    )


invNames =  Table('invNames', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('itemName', VARCHAR(length=200), primary_key=False, nullable=False),


    )


invPositions =  Table('invPositions', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('x', FLOAT(), primary_key=False, nullable=False, default=text(u"'0'")),
            Column('y', FLOAT(), primary_key=False, nullable=False, default=text(u"'0'")),
            Column('z', FLOAT(), primary_key=False, nullable=False, default=text(u"'0'")),
            Column('yaw', FLOAT(precision=24, scale=0), primary_key=False),
            Column('pitch', FLOAT(precision=24, scale=0), primary_key=False),
            Column('roll', FLOAT(precision=24, scale=0), primary_key=False),


    )


invTraits =  Table('invTraits', metadata,
    Column('traitID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=False),
            Column('skillID', INTEGER(), primary_key=False),
            Column('bonus', FLOAT(), primary_key=False),
            Column('bonusText', TEXT(), primary_key=False),
            Column('unitID', INTEGER(), primary_key=False),


    )


invTypeMaterials =  Table('invTypeMaterials', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('materialTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER(), primary_key=False, nullable=False, default=text(u"'0'")),


    )


invTypeReactions =  Table('invTypeReactions', metadata,
    Column('reactionTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('input', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER(), primary_key=False),


    )


invTypes =  Table('invTypes', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('groupID', INTEGER(), primary_key=False),
            Column('typeName', VARCHAR(length=100), primary_key=False),
            Column('description', TEXT(), primary_key=False),
            Column('mass', FLOAT(), primary_key=False),
            Column('volume', FLOAT(), primary_key=False),
            Column('capacity', FLOAT(), primary_key=False),
            Column('portionSize', INTEGER(), primary_key=False),
            Column('raceID', INTEGER(), primary_key=False),
            Column('basePrice', DECIMAL(precision=19, scale=4), primary_key=False),
            Column('published', INTEGER(), primary_key=False),
            Column('marketGroupID', INTEGER(), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),
            Column('soundID', INTEGER(), primary_key=False),
            Column('graphicID', INTEGER(), primary_key=False),


    )


invUniqueNames =  Table('invUniqueNames', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('itemName', VARCHAR(length=200), primary_key=False, nullable=False),
            Column('groupID', INTEGER(), primary_key=False),


    )


invVolumes =  Table('invVolumes', metadata,
    Column('typeid', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('volume', INTEGER(), primary_key=False),


    )


mapCelestialStatistics =  Table('mapCelestialStatistics', metadata,
    Column('celestialID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('temperature', FLOAT(), primary_key=False),
            Column('spectralClass', VARCHAR(length=10), primary_key=False),
            Column('luminosity', FLOAT(), primary_key=False),
            Column('age', FLOAT(), primary_key=False),
            Column('life', FLOAT(), primary_key=False),
            Column('orbitRadius', FLOAT(), primary_key=False),
            Column('eccentricity', FLOAT(), primary_key=False),
            Column('massDust', FLOAT(), primary_key=False),
            Column('massGas', FLOAT(), primary_key=False),
            Column('fragmented', INTEGER(), primary_key=False),
            Column('density', FLOAT(), primary_key=False),
            Column('surfaceGravity', FLOAT(), primary_key=False),
            Column('escapeVelocity', FLOAT(), primary_key=False),
            Column('orbitPeriod', FLOAT(), primary_key=False),
            Column('rotationRate', FLOAT(), primary_key=False),
            Column('locked', INTEGER(), primary_key=False),
            Column('pressure', INTEGER(), primary_key=False),
            Column('radius', INTEGER(), primary_key=False),
            Column('mass', INTEGER(), primary_key=False),


    )


mapConstellationJumps =  Table('mapConstellationJumps', metadata,
    Column('fromRegionID', INTEGER(), primary_key=False),
            Column('fromConstellationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toConstellationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toRegionID', INTEGER(), primary_key=False),


    )


mapConstellations =  Table('mapConstellations', metadata,
    Column('regionID', INTEGER(), primary_key=False),
            Column('constellationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('constellationName', VARCHAR(length=100), primary_key=False),
            Column('x', FLOAT(), primary_key=False),
            Column('y', FLOAT(), primary_key=False),
            Column('z', FLOAT(), primary_key=False),
            Column('xMin', FLOAT(), primary_key=False),
            Column('xMax', FLOAT(), primary_key=False),
            Column('yMin', FLOAT(), primary_key=False),
            Column('yMax', FLOAT(), primary_key=False),
            Column('zMin', FLOAT(), primary_key=False),
            Column('zMax', FLOAT(), primary_key=False),
            Column('factionID', INTEGER(), primary_key=False),
            Column('radius', FLOAT(), primary_key=False),


    )


mapDenormalize =  Table('mapDenormalize', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=False),
            Column('groupID', INTEGER(), primary_key=False),
            Column('solarSystemID', INTEGER(), primary_key=False),
            Column('constellationID', INTEGER(), primary_key=False),
            Column('regionID', INTEGER(), primary_key=False),
            Column('orbitID', INTEGER(), primary_key=False),
            Column('x', FLOAT(), primary_key=False),
            Column('y', FLOAT(), primary_key=False),
            Column('z', FLOAT(), primary_key=False),
            Column('radius', FLOAT(), primary_key=False),
            Column('itemName', VARCHAR(length=100), primary_key=False),
            Column('security', FLOAT(), primary_key=False),
            Column('celestialIndex', INTEGER(), primary_key=False),
            Column('orbitIndex', INTEGER(), primary_key=False),


    )


mapJumps =  Table('mapJumps', metadata,
    Column('stargateID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('destinationID', INTEGER(), primary_key=False),


    )


mapLandmarks =  Table('mapLandmarks', metadata,
    Column('landmarkID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('landmarkName', VARCHAR(length=100), primary_key=False),
            Column('description', TEXT(), primary_key=False),
            Column('locationID', INTEGER(), primary_key=False),
            Column('x', FLOAT(), primary_key=False),
            Column('y', FLOAT(), primary_key=False),
            Column('z', FLOAT(), primary_key=False),
            Column('iconID', INTEGER(), primary_key=False),


    )


mapLocationScenes =  Table('mapLocationScenes', metadata,
    Column('locationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('graphicID', INTEGER(), primary_key=False),


    )


mapLocationWormholeClasses =  Table('mapLocationWormholeClasses', metadata,
    Column('locationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('wormholeClassID', INTEGER(), primary_key=False),


    )


mapRegionJumps =  Table('mapRegionJumps', metadata,
    Column('fromRegionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toRegionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


mapRegions =  Table('mapRegions', metadata,
    Column('regionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('regionName', VARCHAR(length=100), primary_key=False),
            Column('x', FLOAT(), primary_key=False),
            Column('y', FLOAT(), primary_key=False),
            Column('z', FLOAT(), primary_key=False),
            Column('xMin', FLOAT(), primary_key=False),
            Column('xMax', FLOAT(), primary_key=False),
            Column('yMin', FLOAT(), primary_key=False),
            Column('yMax', FLOAT(), primary_key=False),
            Column('zMin', FLOAT(), primary_key=False),
            Column('zMax', FLOAT(), primary_key=False),
            Column('factionID', INTEGER(), primary_key=False),
            Column('radius', FLOAT(), primary_key=False),


    )


mapSolarSystemJumps =  Table('mapSolarSystemJumps', metadata,
    Column('fromRegionID', INTEGER(), primary_key=False),
            Column('fromConstellationID', INTEGER(), primary_key=False),
            Column('fromSolarSystemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toSolarSystemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toConstellationID', INTEGER(), primary_key=False),
            Column('toRegionID', INTEGER(), primary_key=False),


    )


mapSolarSystems =  Table('mapSolarSystems', metadata,
    Column('regionID', INTEGER(), primary_key=False),
            Column('constellationID', INTEGER(), primary_key=False),
            Column('solarSystemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('solarSystemName', VARCHAR(length=100), primary_key=False),
            Column('x', FLOAT(), primary_key=False),
            Column('y', FLOAT(), primary_key=False),
            Column('z', FLOAT(), primary_key=False),
            Column('xMin', FLOAT(), primary_key=False),
            Column('xMax', FLOAT(), primary_key=False),
            Column('yMin', FLOAT(), primary_key=False),
            Column('yMax', FLOAT(), primary_key=False),
            Column('zMin', FLOAT(), primary_key=False),
            Column('zMax', FLOAT(), primary_key=False),
            Column('luminosity', FLOAT(), primary_key=False),
            Column('border', INTEGER(), primary_key=False),
            Column('fringe', INTEGER(), primary_key=False),
            Column('corridor', INTEGER(), primary_key=False),
            Column('hub', INTEGER(), primary_key=False),
            Column('international', INTEGER(), primary_key=False),
            Column('regional', INTEGER(), primary_key=False),
            Column('constellation', INTEGER(), primary_key=False),
            Column('security', FLOAT(), primary_key=False),
            Column('factionID', INTEGER(), primary_key=False),
            Column('radius', FLOAT(), primary_key=False),
            Column('sunTypeID', INTEGER(), primary_key=False),
            Column('securityClass', VARCHAR(length=2), primary_key=False),


    )


mapUniverse =  Table('mapUniverse', metadata,
    Column('universeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('universeName', VARCHAR(length=100), primary_key=False),
            Column('x', FLOAT(), primary_key=False),
            Column('y', FLOAT(), primary_key=False),
            Column('z', FLOAT(), primary_key=False),
            Column('xMin', FLOAT(), primary_key=False),
            Column('xMax', FLOAT(), primary_key=False),
            Column('yMin', FLOAT(), primary_key=False),
            Column('yMax', FLOAT(), primary_key=False),
            Column('zMin', FLOAT(), primary_key=False),
            Column('zMax', FLOAT(), primary_key=False),
            Column('radius', FLOAT(), primary_key=False),


    )


planetSchematics =  Table('planetSchematics', metadata,
    Column('schematicID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('schematicName', VARCHAR(length=255), primary_key=False),
            Column('cycleTime', INTEGER(), primary_key=False),


    )


planetSchematicsPinMap =  Table('planetSchematicsPinMap', metadata,
    Column('schematicID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('pinTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


planetSchematicsTypeMap =  Table('planetSchematicsTypeMap', metadata,
    Column('schematicID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER(), primary_key=False),
            Column('isInput', INTEGER(), primary_key=False),


    )


ramActivities =  Table('ramActivities', metadata,
    Column('activityID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('activityName', VARCHAR(length=100), primary_key=False),
            Column('iconNo', VARCHAR(length=5), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('published', INTEGER(), primary_key=False),


    )


ramAssemblyLineStations =  Table('ramAssemblyLineStations', metadata,
    Column('stationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER(), primary_key=False),
            Column('stationTypeID', INTEGER(), primary_key=False),
            Column('ownerID', INTEGER(), primary_key=False),
            Column('solarSystemID', INTEGER(), primary_key=False),
            Column('regionID', INTEGER(), primary_key=False),


    )


ramAssemblyLineTypeDetailPerCategory =  Table('ramAssemblyLineTypeDetailPerCategory', metadata,
    Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('categoryID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('timeMultiplier', FLOAT(), primary_key=False),
            Column('materialMultiplier', FLOAT(), primary_key=False),
            Column('costMultiplier', FLOAT(), primary_key=False),


    )


ramAssemblyLineTypeDetailPerGroup =  Table('ramAssemblyLineTypeDetailPerGroup', metadata,
    Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('groupID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('timeMultiplier', FLOAT(), primary_key=False),
            Column('materialMultiplier', FLOAT(), primary_key=False),
            Column('costMultiplier', FLOAT(), primary_key=False),


    )


ramAssemblyLineTypes =  Table('ramAssemblyLineTypes', metadata,
    Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('assemblyLineTypeName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('baseTimeMultiplier', FLOAT(), primary_key=False),
            Column('baseMaterialMultiplier', FLOAT(), primary_key=False),
            Column('baseCostMultiplier', FLOAT(), primary_key=False),
            Column('volume', FLOAT(), primary_key=False),
            Column('activityID', INTEGER(), primary_key=False),
            Column('minCostPerHour', FLOAT(), primary_key=False),


    )


ramInstallationTypeContents =  Table('ramInstallationTypeContents', metadata,
    Column('installationTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER(), primary_key=False),


    )


skinLicense =  Table('skinLicense', metadata,
    Column('licenseTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('duration', INTEGER(), primary_key=False),
            Column('skinID', INTEGER(), primary_key=False),


    )


skinMaterials =  Table('skinMaterials', metadata,
    Column('skinMaterialID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('displayNameID', INTEGER(), primary_key=False),
            Column('materialSetID', INTEGER(), primary_key=False),


    )


skinShip =  Table('skinShip', metadata,
    Column('skinID', INTEGER(), primary_key=False),
            Column('typeID', INTEGER(), primary_key=False),


    )


skins =  Table('skins', metadata,
    Column('skinID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('internalName', VARCHAR(length=70), primary_key=False),
            Column('skinMaterialID', INTEGER(), primary_key=False),


    )


staOperationServices =  Table('staOperationServices', metadata,
    Column('operationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('serviceID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


staOperations =  Table('staOperations', metadata,
    Column('activityID', INTEGER(), primary_key=False),
            Column('operationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('operationName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),
            Column('fringe', INTEGER(), primary_key=False),
            Column('corridor', INTEGER(), primary_key=False),
            Column('hub', INTEGER(), primary_key=False),
            Column('border', INTEGER(), primary_key=False),
            Column('ratio', INTEGER(), primary_key=False),
            Column('caldariStationTypeID', INTEGER(), primary_key=False),
            Column('minmatarStationTypeID', INTEGER(), primary_key=False),
            Column('amarrStationTypeID', INTEGER(), primary_key=False),
            Column('gallenteStationTypeID', INTEGER(), primary_key=False),
            Column('joveStationTypeID', INTEGER(), primary_key=False),


    )


staServices =  Table('staServices', metadata,
    Column('serviceID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('serviceName', VARCHAR(length=100), primary_key=False),
            Column('description', VARCHAR(length=1000), primary_key=False),


    )


staStationTypes =  Table('staStationTypes', metadata,
    Column('stationTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('dockEntryX', FLOAT(), primary_key=False),
            Column('dockEntryY', FLOAT(), primary_key=False),
            Column('dockEntryZ', FLOAT(), primary_key=False),
            Column('dockOrientationX', FLOAT(), primary_key=False),
            Column('dockOrientationY', FLOAT(), primary_key=False),
            Column('dockOrientationZ', FLOAT(), primary_key=False),
            Column('operationID', INTEGER(), primary_key=False),
            Column('officeSlots', INTEGER(), primary_key=False),
            Column('reprocessingEfficiency', FLOAT(), primary_key=False),
            Column('conquerable', INTEGER(), primary_key=False),


    )


staStations =  Table('staStations', metadata,
    Column('stationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('security', INTEGER(), primary_key=False),
            Column('dockingCostPerVolume', FLOAT(), primary_key=False),
            Column('maxShipVolumeDockable', FLOAT(), primary_key=False),
            Column('officeRentalCost', INTEGER(), primary_key=False),
            Column('operationID', INTEGER(), primary_key=False),
            Column('stationTypeID', INTEGER(), primary_key=False),
            Column('corporationID', INTEGER(), primary_key=False),
            Column('solarSystemID', INTEGER(), primary_key=False),
            Column('constellationID', INTEGER(), primary_key=False),
            Column('regionID', INTEGER(), primary_key=False),
            Column('stationName', VARCHAR(length=100), primary_key=False),
            Column('x', FLOAT(), primary_key=False),
            Column('y', FLOAT(), primary_key=False),
            Column('z', FLOAT(), primary_key=False),
            Column('reprocessingEfficiency', FLOAT(), primary_key=False),
            Column('reprocessingStationsTake', FLOAT(), primary_key=False),
            Column('reprocessingHangarFlag', INTEGER(), primary_key=False),


    )


translationTables =  Table('translationTables', metadata,
    Column('sourceTable', VARCHAR(length=200), primary_key=True, autoincrement=False, nullable=False),
            Column('destinationTable', VARCHAR(length=200), primary_key=False),
            Column('translatedKey', VARCHAR(length=200), primary_key=True, autoincrement=False, nullable=False),
            Column('tcGroupID', INTEGER(), primary_key=False),
            Column('tcID', INTEGER(), primary_key=False),


    )


trnTranslationColumns =  Table('trnTranslationColumns', metadata,
    Column('tcGroupID', INTEGER(), primary_key=False),
            Column('tcID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('tableName', VARCHAR(length=256), primary_key=False, nullable=False),
            Column('columnName', VARCHAR(length=128), primary_key=False, nullable=False),
            Column('masterID', VARCHAR(length=128), primary_key=False),


    )


trnTranslationLanguages =  Table('trnTranslationLanguages', metadata,
    Column('numericLanguageID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('languageID', VARCHAR(length=50), primary_key=False),
            Column('languageName', VARCHAR(length=200), primary_key=False),


    )


trnTranslations =  Table('trnTranslations', metadata,
    Column('tcID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('keyID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('languageID', VARCHAR(length=50), primary_key=True, autoincrement=False, nullable=False),
            Column('text', TEXT(), primary_key=False, nullable=False),


    )


warCombatZoneSystems =  Table('warCombatZoneSystems', metadata,
    Column('solarSystemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('combatZoneID', INTEGER(), primary_key=False),


    )


warCombatZones =  Table('warCombatZones', metadata,
    Column('combatZoneID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('combatZoneName', VARCHAR(length=100), primary_key=False),
            Column('factionID', INTEGER(), primary_key=False),
            Column('centerSystemID', INTEGER(), primary_key=False),
            Column('description', VARCHAR(length=500), primary_key=False),


    )
