# -*- coding: utf-8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *


metadata = MetaData()


agtAgentTypes =  Table('agtAgentTypes', metadata,
    Column('agentTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('agentType', VARCHAR(length=50))
    )


agtAgents =  Table('agtAgents', metadata,
    Column('agentID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('divisionID', INTEGER()),
            Column('corporationID', INTEGER()),
            Column('locationID', INTEGER()),
            Column('level', INTEGER()),
            Column('quality', INTEGER()),
            Column('agentTypeID', INTEGER()),
            Column('isLocator', INTEGER()),


    )


agtResearchAgents =  Table('agtResearchAgents', metadata,
    Column('agentID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


certCerts =  Table('certCerts', metadata,
    Column('certID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('description',UnicodeText()),
            Column('groupID', INTEGER()),
            Column('name', VARCHAR(length=255)),


    )


certMasteries =  Table('certMasteries', metadata,
    Column('typeID', INTEGER()),
            Column('masteryLevel', INTEGER()),
            Column('certID', INTEGER()),


    )


certSkills =  Table('certSkills', metadata,
    Column('certID', INTEGER()),
            Column('skillID', INTEGER()),
            Column('certLevelInt', INTEGER()),
            Column('skillLevel', INTEGER()),
            Column('certLevelText', VARCHAR(length=8)),


    )


chrAncestries =  Table('chrAncestries', metadata,
    Column('ancestryID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('ancestryName', VARCHAR(length=100)),
            Column('bloodlineID', INTEGER()),
            Column('description', VARCHAR(length=1000)),
            Column('perception', INTEGER()),
            Column('willpower', INTEGER()),
            Column('charisma', INTEGER()),
            Column('memory', INTEGER()),
            Column('intelligence', INTEGER()),
            Column('iconID', INTEGER()),
            Column('shortDescription', VARCHAR(length=500)),


    )


chrAttributes =  Table('chrAttributes', metadata,
    Column('attributeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('attributeName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),
            Column('iconID', INTEGER()),
            Column('shortDescription', VARCHAR(length=500)),
            Column('notes', VARCHAR(length=500)),


    )


chrBloodlines =  Table('chrBloodlines', metadata,
    Column('bloodlineID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('bloodlineName', VARCHAR(length=100)),
            Column('raceID', INTEGER()),
            Column('description', VARCHAR(length=1000)),
            Column('maleDescription', VARCHAR(length=1000)),
            Column('femaleDescription', VARCHAR(length=1000)),
            Column('shipTypeID', INTEGER()),
            Column('corporationID', INTEGER()),
            Column('perception', INTEGER()),
            Column('willpower', INTEGER()),
            Column('charisma', INTEGER()),
            Column('memory', INTEGER()),
            Column('intelligence', INTEGER()),
            Column('iconID', INTEGER()),
            Column('shortDescription', VARCHAR(length=500)),
            Column('shortMaleDescription', VARCHAR(length=500)),
            Column('shortFemaleDescription', VARCHAR(length=500)),


    )


chrFactions =  Table('chrFactions', metadata,
    Column('factionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('factionName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),
            Column('raceIDs', INTEGER()),
            Column('solarSystemID', INTEGER()),
            Column('corporationID', INTEGER()),
            Column('sizeFactor', FLOAT()),
            Column('stationCount', INTEGER()),
            Column('stationSystemCount', INTEGER()),
            Column('militiaCorporationID', INTEGER()),
            Column('iconID', INTEGER()),


    )


chrRaces =  Table('chrRaces', metadata,
    Column('raceID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('raceName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),
            Column('iconID', INTEGER()),
            Column('shortDescription', VARCHAR(length=500)),


    )


crpActivities =  Table('crpActivities', metadata,
    Column('activityID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('activityName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),


    )


crpNPCCorporationDivisions =  Table('crpNPCCorporationDivisions', metadata,
    Column('corporationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('divisionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('size', INTEGER()),


    )


crpNPCCorporationResearchFields =  Table('crpNPCCorporationResearchFields', metadata,
    Column('skillID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('corporationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


crpNPCCorporationTrades =  Table('crpNPCCorporationTrades', metadata,
    Column('corporationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


crpNPCCorporations =  Table('crpNPCCorporations', metadata,
    Column('corporationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('size', CHAR(length=1)),
            Column('extent', CHAR(length=1)),
            Column('solarSystemID', INTEGER()),
            Column('investorID1', INTEGER()),
            Column('investorShares1', INTEGER()),
            Column('investorID2', INTEGER()),
            Column('investorShares2', INTEGER()),
            Column('investorID3', INTEGER()),
            Column('investorShares3', INTEGER()),
            Column('investorID4', INTEGER()),
            Column('investorShares4', INTEGER()),
            Column('friendID', INTEGER()),
            Column('enemyID', INTEGER()),
            Column('publicShares', INTEGER()),
            Column('initialPrice', INTEGER()),
            Column('minSecurity', FLOAT()),
            Column('scattered', INTEGER()),
            Column('fringe', INTEGER()),
            Column('corridor', INTEGER()),
            Column('hub', INTEGER()),
            Column('border', INTEGER()),
            Column('factionID', INTEGER()),
            Column('sizeFactor', FLOAT()),
            Column('stationCount', INTEGER()),
            Column('stationSystemCount', INTEGER()),
            Column('description', VARCHAR(length=4000)),
            Column('iconID', INTEGER()),


    )


crpNPCDivisions =  Table('crpNPCDivisions', metadata,
    Column('divisionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('divisionName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),
            Column('leaderType', VARCHAR(length=100)),


    )


dgmAttributeCategories =  Table('dgmAttributeCategories', metadata,
    Column('categoryID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('categoryName', VARCHAR(length=50)),
            Column('categoryDescription', VARCHAR(length=200)),


    )


dgmAttributeTypes =  Table('dgmAttributeTypes', metadata,
    Column('attributeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('attributeName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),
            Column('iconID', INTEGER()),
            Column('defaultValue', FLOAT()),
            Column('published', INTEGER()),
            Column('displayName', VARCHAR(length=100)),
            Column('unitID', INTEGER()),
            Column('stackable', INTEGER()),
            Column('highIsGood', INTEGER()),
            Column('categoryID', INTEGER()),


    )


dgmEffects =  Table('dgmEffects', metadata,
    Column('effectID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('effectName', VARCHAR(length=400)),
            Column('effectCategory', INTEGER()),
            Column('preExpression', INTEGER()),
            Column('postExpression', INTEGER()),
            Column('description', VARCHAR(length=1000)),
            Column('guid', VARCHAR(length=60)),
            Column('iconID', INTEGER()),
            Column('isOffensive', INTEGER()),
            Column('isAssistance', INTEGER()),
            Column('durationAttributeID', INTEGER()),
            Column('trackingSpeedAttributeID', INTEGER()),
            Column('dischargeAttributeID', INTEGER()),
            Column('rangeAttributeID', INTEGER()),
            Column('falloffAttributeID', INTEGER()),
            Column('disallowAutoRepeat', INTEGER()),
            Column('published', INTEGER()),
            Column('displayName', VARCHAR(length=100)),
            Column('isWarpSafe', INTEGER()),
            Column('rangeChance', INTEGER()),
            Column('electronicChance', INTEGER()),
            Column('propulsionChance', INTEGER()),
            Column('distribution', INTEGER()),
            Column('sfxName', VARCHAR(length=20)),
            Column('npcUsageChanceAttributeID', INTEGER()),
            Column('npcActivationChanceAttributeID', INTEGER()),
            Column('fittingUsageChanceAttributeID', INTEGER()),
            Column('modifierInfo',UnicodeText()),


    )


dgmExpressions =  Table('dgmExpressions', metadata,
    Column('expressionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('operandID', INTEGER()),
            Column('arg1', INTEGER()),
            Column('arg2', INTEGER()),
            Column('expressionValue', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),
            Column('expressionName', VARCHAR(length=500)),
            Column('expressionTypeID', INTEGER()),
            Column('expressionGroupID', INTEGER()),
            Column('expressionAttributeID', INTEGER()),


    )


dgmTypeAttributes =  Table('dgmTypeAttributes', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('attributeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('valueInt', INTEGER()),
            Column('valueFloat', FLOAT()),


    )


dgmTypeEffects =  Table('dgmTypeEffects', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('effectID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('isDefault', INTEGER()),


    )


eveGraphics =  Table('eveGraphics', metadata,
    Column('graphicID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('sofFactionName', VARCHAR(length=100)),
            Column('graphicFile', VARCHAR(length=100)),
            Column('sofHullName', VARCHAR(length=100)),
            Column('sofRaceName', VARCHAR(length=100)),
            Column('description',UnicodeText()),


    )


eveIcons =  Table('eveIcons', metadata,
    Column('iconID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('iconFile', VARCHAR(length=500)),
            Column('description',UnicodeText()),


    )


eveUnits =  Table('eveUnits', metadata,
    Column('unitID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('unitName', VARCHAR(length=100)),
            Column('displayName', VARCHAR(length=50)),
            Column('description', VARCHAR(length=1000)),


    )


industryActivity =  Table('industryActivity', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('activityID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('time', INTEGER())
    )


industryActivityMaterials =  Table('industryActivityMaterials', metadata,
    Column('typeID', INTEGER()),
            Column('activityID', INTEGER()),
            Column('materialTypeID', INTEGER()),
            Column('quantity', INTEGER()),


    )


industryActivityProbabilities =  Table('industryActivityProbabilities', metadata,
    Column('typeID', INTEGER()),
            Column('activityID', INTEGER()),
            Column('productTypeID', INTEGER()),
            Column('probability', DECIMAL(precision=3, scale=2)),


    )


industryActivityProducts =  Table('industryActivityProducts', metadata,
    Column('typeID', INTEGER()),
            Column('activityID', INTEGER()),
            Column('productTypeID', INTEGER()),
            Column('quantity', INTEGER()),


    )


industryActivityRaces =  Table('industryActivityRaces', metadata,
    Column('typeID', INTEGER()),
            Column('activityID', INTEGER()),
            Column('productTypeID', INTEGER()),
            Column('raceID', INTEGER()),


    )


industryActivitySkills =  Table('industryActivitySkills', metadata,
    Column('typeID', INTEGER()),
            Column('activityID', INTEGER()),
            Column('skillID', INTEGER()),
            Column('level', INTEGER()),


    )


industryBlueprints =  Table('industryBlueprints', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('maxProductionLimit', INTEGER()),


    )


invCategories =  Table('invCategories', metadata,
    Column('categoryID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('categoryName', VARCHAR(length=100)),
            Column('iconID', INTEGER()),
            Column('published', INTEGER()),


    )


invContrabandTypes =  Table('invContrabandTypes', metadata,
    Column('factionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('standingLoss', FLOAT()),
            Column('confiscateMinSec', FLOAT()),
            Column('fineByValue', FLOAT()),
            Column('attackMinSec', FLOAT()),


    )


invControlTowerResourcePurposes =  Table('invControlTowerResourcePurposes', metadata,
    Column('purpose', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('purposeText', VARCHAR(length=100)),


    )


invControlTowerResources =  Table('invControlTowerResources', metadata,
    Column('controlTowerTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('resourceTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('purpose', INTEGER()),
            Column('quantity', INTEGER()),
            Column('minSecurityLevel', FLOAT()),
            Column('factionID', INTEGER()),


    )


invFlags =  Table('invFlags', metadata,
    Column('flagID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('flagName', VARCHAR(length=200)),
            Column('flagText', VARCHAR(length=100)),
            Column('orderID', INTEGER()),


    )


invGroups =  Table('invGroups', metadata,
    Column('groupID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('categoryID', INTEGER()),
            Column('groupName', VARCHAR(length=100)),
            Column('iconID', INTEGER()),
            Column('useBasePrice', INTEGER()),
            Column('anchored', INTEGER()),
            Column('anchorable', INTEGER()),
            Column('fittableNonSingleton', INTEGER()),
            Column('published', INTEGER()),


    )


invItems =  Table('invItems', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), nullable=False),
            Column('ownerID', INTEGER(), nullable=False),
            Column('locationID', INTEGER(), nullable=False),
            Column('flagID', INTEGER(), nullable=False),
            Column('quantity', INTEGER(), nullable=False),


    )


invMarketGroups =  Table('invMarketGroups', metadata,
    Column('marketGroupID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('parentGroupID', INTEGER()),
            Column('marketGroupName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=3000)),
            Column('iconID', INTEGER()),
            Column('hasTypes', INTEGER()),


    )


invMetaGroups =  Table('invMetaGroups', metadata,
    Column('metaGroupID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('metaGroupName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),
            Column('iconID', INTEGER()),


    )


invMetaTypes =  Table('invMetaTypes', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('parentTypeID', INTEGER()),
            Column('metaGroupID', INTEGER()),


    )


invNames =  Table('invNames', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('itemName', VARCHAR(length=200), nullable=False),


    )


invPositions =  Table('invPositions', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('x', FLOAT(), nullable=False, default=text(u"'0'")),
            Column('y', FLOAT(), nullable=False, default=text(u"'0'")),
            Column('z', FLOAT(), nullable=False, default=text(u"'0'")),
            Column('yaw', FLOAT(precision=24, scale=0)),
            Column('pitch', FLOAT(precision=24, scale=0)),
            Column('roll', FLOAT(precision=24, scale=0)),


    )


invTraits =  Table('invTraits', metadata,
    Column('traitID', INTEGER(), primary_key=True, autoincrement=True, nullable=False),
            Column('typeID', INTEGER()),
            Column('skillID', INTEGER()),
            Column('bonus', FLOAT()),
            Column('bonusText',UnicodeText()),
            Column('unitID', INTEGER()),


    )


invTypeMaterials =  Table('invTypeMaterials', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('materialTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER(), nullable=False, default=text(u"'0'")),


    )


invTypeReactions =  Table('invTypeReactions', metadata,
    Column('reactionTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('input', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER()),


    )


invTypes =  Table('invTypes', metadata,
    Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('groupID', INTEGER()),
            Column('typeName', VARCHAR(length=100)),
            Column('description',UnicodeText()),
            Column('mass', FLOAT()),
            Column('volume', FLOAT()),
            Column('capacity', FLOAT()),
            Column('portionSize', INTEGER()),
            Column('raceID', INTEGER()),
            Column('basePrice', DECIMAL(precision=19, scale=4)),
            Column('published', INTEGER()),
            Column('marketGroupID', INTEGER()),
            Column('iconID', INTEGER()),
            Column('soundID', INTEGER()),
            Column('graphicID', INTEGER()),


    )


invUniqueNames =  Table('invUniqueNames', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('itemName', VARCHAR(length=200), nullable=False),
            Column('groupID', INTEGER()),


    )


invVolumes =  Table('invVolumes', metadata,
    Column('typeid', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('volume', INTEGER()),


    )


mapCelestialStatistics =  Table('mapCelestialStatistics', metadata,
    Column('celestialID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('temperature', FLOAT()),
            Column('spectralClass', VARCHAR(length=10)),
            Column('luminosity', FLOAT()),
            Column('age', FLOAT()),
            Column('life', FLOAT()),
            Column('orbitRadius', FLOAT()),
            Column('eccentricity', FLOAT()),
            Column('massDust', FLOAT()),
            Column('massGas', FLOAT()),
            Column('fragmented', INTEGER()),
            Column('density', FLOAT()),
            Column('surfaceGravity', FLOAT()),
            Column('escapeVelocity', FLOAT()),
            Column('orbitPeriod', FLOAT()),
            Column('rotationRate', FLOAT()),
            Column('locked', INTEGER()),
            Column('pressure', INTEGER()),
            Column('radius', INTEGER()),
            Column('mass', INTEGER()),


    )


mapConstellationJumps =  Table('mapConstellationJumps', metadata,
    Column('fromRegionID', INTEGER()),
            Column('fromConstellationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toConstellationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toRegionID', INTEGER()),


    )


mapConstellations =  Table('mapConstellations', metadata,
    Column('regionID', INTEGER()),
            Column('constellationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('constellationName', VARCHAR(length=100)),
            Column('x', FLOAT()),
            Column('y', FLOAT()),
            Column('z', FLOAT()),
            Column('xMin', FLOAT()),
            Column('xMax', FLOAT()),
            Column('yMin', FLOAT()),
            Column('yMax', FLOAT()),
            Column('zMin', FLOAT()),
            Column('zMax', FLOAT()),
            Column('factionID', INTEGER()),
            Column('radius', FLOAT()),


    )


mapDenormalize =  Table('mapDenormalize', metadata,
    Column('itemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER()),
            Column('groupID', INTEGER()),
            Column('solarSystemID', INTEGER()),
            Column('constellationID', INTEGER()),
            Column('regionID', INTEGER()),
            Column('orbitID', INTEGER()),
            Column('x', FLOAT()),
            Column('y', FLOAT()),
            Column('z', FLOAT()),
            Column('radius', FLOAT()),
            Column('itemName', VARCHAR(length=100)),
            Column('security', FLOAT()),
            Column('celestialIndex', INTEGER()),
            Column('orbitIndex', INTEGER()),


    )


mapJumps =  Table('mapJumps', metadata,
    Column('stargateID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('destinationID', INTEGER()),


    )


mapLandmarks =  Table('mapLandmarks', metadata,
    Column('landmarkID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('landmarkName', VARCHAR(length=100)),
            Column('description',UnicodeText()),
            Column('locationID', INTEGER()),
            Column('x', FLOAT()),
            Column('y', FLOAT()),
            Column('z', FLOAT()),
            Column('iconID', INTEGER()),


    )


mapLocationScenes =  Table('mapLocationScenes', metadata,
    Column('locationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('graphicID', INTEGER()),


    )


mapLocationWormholeClasses =  Table('mapLocationWormholeClasses', metadata,
    Column('locationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('wormholeClassID', INTEGER()),


    )


mapRegionJumps =  Table('mapRegionJumps', metadata,
    Column('fromRegionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toRegionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


mapRegions =  Table('mapRegions', metadata,
    Column('regionID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('regionName', VARCHAR(length=100)),
            Column('x', FLOAT()),
            Column('y', FLOAT()),
            Column('z', FLOAT()),
            Column('xMin', FLOAT()),
            Column('xMax', FLOAT()),
            Column('yMin', FLOAT()),
            Column('yMax', FLOAT()),
            Column('zMin', FLOAT()),
            Column('zMax', FLOAT()),
            Column('factionID', INTEGER()),
            Column('radius', FLOAT()),


    )


mapSolarSystemJumps =  Table('mapSolarSystemJumps', metadata,
    Column('fromRegionID', INTEGER()),
            Column('fromConstellationID', INTEGER()),
            Column('fromSolarSystemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toSolarSystemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('toConstellationID', INTEGER()),
            Column('toRegionID', INTEGER()),


    )


mapSolarSystems =  Table('mapSolarSystems', metadata,
    Column('regionID', INTEGER()),
            Column('constellationID', INTEGER()),
            Column('solarSystemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('solarSystemName', VARCHAR(length=100)),
            Column('x', FLOAT()),
            Column('y', FLOAT()),
            Column('z', FLOAT()),
            Column('xMin', FLOAT()),
            Column('xMax', FLOAT()),
            Column('yMin', FLOAT()),
            Column('yMax', FLOAT()),
            Column('zMin', FLOAT()),
            Column('zMax', FLOAT()),
            Column('luminosity', FLOAT()),
            Column('border', INTEGER()),
            Column('fringe', INTEGER()),
            Column('corridor', INTEGER()),
            Column('hub', INTEGER()),
            Column('international', INTEGER()),
            Column('regional', INTEGER()),
            Column('constellation', INTEGER()),
            Column('security', FLOAT()),
            Column('factionID', INTEGER()),
            Column('radius', FLOAT()),
            Column('sunTypeID', INTEGER()),
            Column('securityClass', VARCHAR(length=2)),


    )


mapUniverse =  Table('mapUniverse', metadata,
    Column('universeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('universeName', VARCHAR(length=100)),
            Column('x', FLOAT()),
            Column('y', FLOAT()),
            Column('z', FLOAT()),
            Column('xMin', FLOAT()),
            Column('xMax', FLOAT()),
            Column('yMin', FLOAT()),
            Column('yMax', FLOAT()),
            Column('zMin', FLOAT()),
            Column('zMax', FLOAT()),
            Column('radius', FLOAT()),


    )


planetSchematics =  Table('planetSchematics', metadata,
    Column('schematicID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('schematicName', VARCHAR(length=255)),
            Column('cycleTime', INTEGER()),


    )


planetSchematicsPinMap =  Table('planetSchematicsPinMap', metadata,
    Column('schematicID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('pinTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


planetSchematicsTypeMap =  Table('planetSchematicsTypeMap', metadata,
    Column('schematicID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('typeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER()),
            Column('isInput', INTEGER()),


    )


ramActivities =  Table('ramActivities', metadata,
    Column('activityID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('activityName', VARCHAR(length=100)),
            Column('iconNo', VARCHAR(length=5)),
            Column('description', VARCHAR(length=1000)),
            Column('published', INTEGER()),


    )


ramAssemblyLineStations =  Table('ramAssemblyLineStations', metadata,
    Column('stationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER()),
            Column('stationTypeID', INTEGER()),
            Column('ownerID', INTEGER()),
            Column('solarSystemID', INTEGER()),
            Column('regionID', INTEGER()),


    )


ramAssemblyLineTypeDetailPerCategory =  Table('ramAssemblyLineTypeDetailPerCategory', metadata,
    Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('categoryID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('timeMultiplier', FLOAT()),
            Column('materialMultiplier', FLOAT()),
            Column('costMultiplier', FLOAT()),


    )


ramAssemblyLineTypeDetailPerGroup =  Table('ramAssemblyLineTypeDetailPerGroup', metadata,
    Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('groupID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('timeMultiplier', FLOAT()),
            Column('materialMultiplier', FLOAT()),
            Column('costMultiplier', FLOAT()),


    )


ramAssemblyLineTypes =  Table('ramAssemblyLineTypes', metadata,
    Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('assemblyLineTypeName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),
            Column('baseTimeMultiplier', FLOAT()),
            Column('baseMaterialMultiplier', FLOAT()),
            Column('baseCostMultiplier', FLOAT()),
            Column('volume', FLOAT()),
            Column('activityID', INTEGER()),
            Column('minCostPerHour', FLOAT()),


    )


ramInstallationTypeContents =  Table('ramInstallationTypeContents', metadata,
    Column('installationTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('assemblyLineTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('quantity', INTEGER()),


    )


skinLicense =  Table('skinLicense', metadata,
    Column('licenseTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('duration', INTEGER()),
            Column('skinID', INTEGER()),


    )


skinMaterials =  Table('skinMaterials', metadata,
    Column('skinMaterialID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('displayNameID', INTEGER()),
            Column('materialSetID', INTEGER()),


    )


skinShip =  Table('skinShip', metadata,
    Column('skinID', INTEGER()),
            Column('typeID', INTEGER()),


    )


skins =  Table('skins', metadata,
    Column('skinID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('internalName', VARCHAR(length=70)),
            Column('skinMaterialID', INTEGER()),


    )


staOperationServices =  Table('staOperationServices', metadata,
    Column('operationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('serviceID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),


    )


staOperations =  Table('staOperations', metadata,
    Column('activityID', INTEGER()),
            Column('operationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('operationName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),
            Column('fringe', INTEGER()),
            Column('corridor', INTEGER()),
            Column('hub', INTEGER()),
            Column('border', INTEGER()),
            Column('ratio', INTEGER()),
            Column('caldariStationTypeID', INTEGER()),
            Column('minmatarStationTypeID', INTEGER()),
            Column('amarrStationTypeID', INTEGER()),
            Column('gallenteStationTypeID', INTEGER()),
            Column('joveStationTypeID', INTEGER()),


    )


staServices =  Table('staServices', metadata,
    Column('serviceID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('serviceName', VARCHAR(length=100)),
            Column('description', VARCHAR(length=1000)),


    )


staStationTypes =  Table('staStationTypes', metadata,
    Column('stationTypeID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('dockEntryX', FLOAT()),
            Column('dockEntryY', FLOAT()),
            Column('dockEntryZ', FLOAT()),
            Column('dockOrientationX', FLOAT()),
            Column('dockOrientationY', FLOAT()),
            Column('dockOrientationZ', FLOAT()),
            Column('operationID', INTEGER()),
            Column('officeSlots', INTEGER()),
            Column('reprocessingEfficiency', FLOAT()),
            Column('conquerable', INTEGER()),


    )


staStations =  Table('staStations', metadata,
    Column('stationID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('security', INTEGER()),
            Column('dockingCostPerVolume', FLOAT()),
            Column('maxShipVolumeDockable', FLOAT()),
            Column('officeRentalCost', INTEGER()),
            Column('operationID', INTEGER()),
            Column('stationTypeID', INTEGER()),
            Column('corporationID', INTEGER()),
            Column('solarSystemID', INTEGER()),
            Column('constellationID', INTEGER()),
            Column('regionID', INTEGER()),
            Column('stationName', VARCHAR(length=100)),
            Column('x', FLOAT()),
            Column('y', FLOAT()),
            Column('z', FLOAT()),
            Column('reprocessingEfficiency', FLOAT()),
            Column('reprocessingStationsTake', FLOAT()),
            Column('reprocessingHangarFlag', INTEGER()),


    )


translationTables =  Table('translationTables', metadata,
    Column('sourceTable', VARCHAR(length=200), primary_key=True, autoincrement=False, nullable=False),
            Column('destinationTable', VARCHAR(length=200)),
            Column('translatedKey', VARCHAR(length=200), primary_key=True, autoincrement=False, nullable=False),
            Column('tcGroupID', INTEGER()),
            Column('tcID', INTEGER()),


    )


trnTranslationColumns =  Table('trnTranslationColumns', metadata,
    Column('tcGroupID', INTEGER()),
            Column('tcID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('tableName', VARCHAR(length=256), nullable=False),
            Column('columnName', VARCHAR(length=128), nullable=False),
            Column('masterID', VARCHAR(length=128)),


    )


trnTranslationLanguages =  Table('trnTranslationLanguages', metadata,
    Column('numericLanguageID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('languageID', VARCHAR(length=50)),
            Column('languageName', VARCHAR(length=200)),


    )


trnTranslations =  Table('trnTranslations', metadata,
    Column('tcID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('keyID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('languageID', VARCHAR(length=50), primary_key=True, autoincrement=False, nullable=False),
            Column('text',UnicodeText(), nullable=False),


    )


warCombatZoneSystems =  Table('warCombatZoneSystems', metadata,
    Column('solarSystemID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('combatZoneID', INTEGER()),


    )


warCombatZones =  Table('warCombatZones', metadata,
    Column('combatZoneID', INTEGER(), primary_key=True, autoincrement=False, nullable=False),
            Column('combatZoneName', VARCHAR(length=100)),
            Column('factionID', INTEGER()),
            Column('centerSystemID', INTEGER()),
            Column('description', VARCHAR(length=500)),


    )
